# Generated by Django 4.1.7 on 2023-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_country_alter_author_date_of_birth_and_more'),
        ('books', '0003_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='authors.author', verbose_name='Автор'),
        ),
    ]
