# Generated by Django 4.1.7 on 2023-03-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_country_alter_author_date_of_birth_and_more'),
        ('books', '0004_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authors.author', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
